### PR TITLE
travel bus image added

### PR DESCRIPTION
**Pull request by atul-kumar02**

### CODE REVIEW

**Comment by atul-kumar02** [comment]
@sukhbir-singh

**Comment by sukhbir-singh** [comment]
Need to change some other icons on the website

**Comment by sukhbir-singh** [comment]
Also make some icons for gallery soon which is to be added for website

**Comment by sukhbir-singh** [comment]
And send me the original icon you have made for this hackathon. I think that was the better icon for hackathon also we have to print it for stickers to be printed as swags.

**Pull request merged**
